### PR TITLE
Run rabix composer as a web application

### PR DESCRIPTION
**Pull request by ghost**
We made the code able to function as a web application.

We add two environment files, add two properties to existing files so the composer can load electron classes/services and other parts, based on a state of those properties. Also, we had created the **IpcWebService** so we can interrupt calls to the electron **ipcRenderer**.

### CODE REVIEW

**Comment by mayacoda** [comment]
Hey @jDatum, thanks for the PR!

Could you give a bit more context concerning this code? We've tried it out, and I'm not sure if we're missing something, but it doesn't seem to be a complete feature. Technically "Run rabix composer as a web application" is an accurate description, but the application (as a CWL editor) isn't functional. You can't actually edit files and some happy path actions throw exceptions, which is unacceptable.

Are there any specifications for this feature? Returning the Rabix Composer to the browser is in our long-term roadmap. It's far from a simple feature to implement, so it would be great if we could agree on how this should be done. Especially seeing as you're already working on the problem.

**Comment by tetron** [comment]
Hi @mayacoda, the background for this is that @jDatum is working with me to integrate Composer as a web app into Arvados.   We want to contribute that work back to main Composer repo so that Composer-as-Electron app and Composer-as-web-app can just be different configurations.  The thought was to contribute the minimal capability of running as a web app to make it easier for you to review and accept, even though it isn't functional on its own.  We are working on file load/edit/save right now.

**Comment by kaushik-work** [comment]
@jDatum , @tetron closing as we discussed: due, unfortunately, to the large mismatch with the current code base.

**Comment by mmm2006** [comment]
@ghost, how can this code run as a web application? Thanks.

**Pull request closed without merging**
